insert into goods values (1,'Tata Tea',6,135,'food');;
insert into goods values (2,'Ashirwad Atta',16,360,'food');
insert into goods values (3,'Basmati rice',13,140,'food');
insert into goods values (4,'Tata chanadal',8,80,'food');
insert into goods values (5,'Besan',12,90,'food');
insert into goods values (6,'Thumbsup',6,,40,'beverages and drinks');
insert into goods values (7,'Pepsi',6,50,'beverages and drinks');
insert into goods values (8,'Amul Lassi',5,20,'beverages and drinks');
insert into goods values (9,'Buttermilk',2,10,'beverages and drinks');
insert into goods values (10,'Milk',2,58,'beverages and drinks');
insert into goods values (11,'Cadbury Silk',9,165,'chocolates');
insert into goods values (12,'kit kat',5,25,'chocolates');
insert into goods values (13,'Milkybar',4,20,'chocolates');
insert into goods values (14,'5star',5,30,'chocolates');
insert into goods values (15,'Perk',2,10,'chocolates');
insert into goods values (16,'Tide',15,140,'cleaning');
insert into goods values (17,'Harpic',15,83,'cleaning');
insert into goods values (18,'Lizol',12,68,'cleaning');
insert into goods values (19,'Domex',14,78,'cleaning');
insert into goods values (20,'Wheel',12,53,'cleaning');
insert into goods values (21,'Vim bar',3,22,'cleaning');

